name: PR approve bypass

on:
  issue_comment:
    types: [created]

jobs:
  bypass-approve:
    if: github.event.issue.pull_request != null && contains(github.event.comment.body, '/bypass-approve')
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Approve PR via API
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            const prNumber = context.issue.number;
            await github.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
              event: 'APPROVE',
              body: '✅ Auto approved by GitHub Actions',
            });
